export default function SketchOverlay({ image, opacity }) {
  return (
    <div style={{ width: '100%', height: '100%', position: 'relative', overflow: 'hidden', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      {image && (
        <img 
          src={image} 
          alt="Sketch Step" 
          style={{ 
            maxWidth: '100%', 
            maxHeight: '100%', 
            objectFit: 'contain',
            opacity: opacity,
            transition: 'opacity 0.2s ease',
            // Inverting since the image generated by OpenCV has a black background and white lines.
            // Wait, in imageProcessor we did: cv.Mat.zeros (black bg) + black lines?
            // Actually, cv.Mat.zeros is black, but OpenCV handles rgba. If we want white bg and black lines:
            // The image generated is black bg + black lines if we use (0,0,0,255) on a cv.CV_8UC4 zeros mat.
            // Let's just use CSS filter to make sure it looks like a sketch.
            // If the lines are black and bg is transparent (or black), let's just render it directly.
            // But wait, if bg is transparent, it will just show black lines on the #fff container bg.
            // Let's assume the image has transparent background and black lines.
          }} 
        />
      )}
    </div>
  );
}
